-- Generated: vehicle models for major brands on Turkish market
-- This file is idempotent: re-running will skip existing (brand, name) pairs

insert into public.vehicle_models (brand_id, name, sort_order, is_active)
select b.id, m.model_name, m.sort_order, true
from (values
  ('BMW'::text, '1 Serisi'::text, 0),
  ('BMW'::text, '2 Serisi'::text, 1),
  ('BMW'::text, '3 Serisi'::text, 2),
  ('BMW'::text, '4 Serisi'::text, 3),
  ('BMW'::text, '5 Serisi'::text, 4),
  ('BMW'::text, '6 Serisi'::text, 5),
  ('BMW'::text, '7 Serisi'::text, 6),
  ('BMW'::text, '8 Serisi'::text, 7),
  ('BMW'::text, 'X1'::text, 8),
  ('BMW'::text, 'X2'::text, 9),
  ('BMW'::text, 'X3'::text, 10),
  ('BMW'::text, 'X4'::text, 11),
  ('BMW'::text, 'X5'::text, 12),
  ('BMW'::text, 'X6'::text, 13),
  ('BMW'::text, 'X7'::text, 14),
  ('BMW'::text, 'XM'::text, 15),
  ('BMW'::text, 'Z3'::text, 16),
  ('BMW'::text, 'Z4'::text, 17),
  ('BMW'::text, 'i3'::text, 18),
  ('BMW'::text, 'i4'::text, 19),
  ('BMW'::text, 'i7'::text, 20),
  ('BMW'::text, 'iX'::text, 21),
  ('BMW'::text, 'iX1'::text, 22),
  ('BMW'::text, 'iX3'::text, 23),
  ('BMW'::text, 'M2'::text, 24),
  ('BMW'::text, 'M3'::text, 25),
  ('BMW'::text, 'M4'::text, 26),
  ('BMW'::text, 'M5'::text, 27),
  ('BMW'::text, 'M8'::text, 28),
  ('Mercedes-Benz'::text, 'A Serisi'::text, 0),
  ('Mercedes-Benz'::text, 'B Serisi'::text, 1),
  ('Mercedes-Benz'::text, 'C Serisi'::text, 2),
  ('Mercedes-Benz'::text, 'CLA'::text, 3),
  ('Mercedes-Benz'::text, 'CLS'::text, 4),
  ('Mercedes-Benz'::text, 'E Serisi'::text, 5),
  ('Mercedes-Benz'::text, 'S Serisi'::text, 6),
  ('Mercedes-Benz'::text, 'G Serisi'::text, 7),
  ('Mercedes-Benz'::text, 'GLA'::text, 8),
  ('Mercedes-Benz'::text, 'GLB'::text, 9),
  ('Mercedes-Benz'::text, 'GLC'::text, 10),
  ('Mercedes-Benz'::text, 'GLE'::text, 11),
  ('Mercedes-Benz'::text, 'GLS'::text, 12),
  ('Mercedes-Benz'::text, 'EQC'::text, 13),
  ('Mercedes-Benz'::text, 'EQE'::text, 14),
  ('Mercedes-Benz'::text, 'EQS'::text, 15),
  ('Mercedes-Benz'::text, 'EQB'::text, 16),
  ('Mercedes-Benz'::text, 'EQA'::text, 17),
  ('Mercedes-Benz'::text, 'AMG GT'::text, 18),
  ('Mercedes-Benz'::text, 'SL'::text, 19),
  ('Mercedes-Benz'::text, 'SLC'::text, 20),
  ('Mercedes-Benz'::text, 'SLK'::text, 21),
  ('Mercedes-Benz'::text, 'V Serisi'::text, 22),
  ('Mercedes-Benz'::text, 'Sprinter'::text, 23),
  ('Mercedes-Benz'::text, 'Citan'::text, 24),
  ('Audi'::text, 'A1'::text, 0),
  ('Audi'::text, 'A3'::text, 1),
  ('Audi'::text, 'A4'::text, 2),
  ('Audi'::text, 'A5'::text, 3),
  ('Audi'::text, 'A6'::text, 4),
  ('Audi'::text, 'A7'::text, 5),
  ('Audi'::text, 'A8'::text, 6),
  ('Audi'::text, 'Q2'::text, 7),
  ('Audi'::text, 'Q3'::text, 8),
  ('Audi'::text, 'Q4 e-tron'::text, 9),
  ('Audi'::text, 'Q5'::text, 10),
  ('Audi'::text, 'Q5 e-tron'::text, 11),
  ('Audi'::text, 'Q7'::text, 12),
  ('Audi'::text, 'Q8'::text, 13),
  ('Audi'::text, 'Q8 e-tron'::text, 14),
  ('Audi'::text, 'TT'::text, 15),
  ('Audi'::text, 'e-tron'::text, 16),
  ('Audi'::text, 'e-tron GT'::text, 17),
  ('Audi'::text, 'RS3'::text, 18),
  ('Audi'::text, 'RS4'::text, 19),
  ('Audi'::text, 'RS5'::text, 20),
  ('Audi'::text, 'RS6'::text, 21),
  ('Audi'::text, 'RS7'::text, 22),
  ('Audi'::text, 'RS Q3'::text, 23),
  ('Audi'::text, 'RS Q8'::text, 24),
  ('Audi'::text, 'S3'::text, 25),
  ('Audi'::text, 'S4'::text, 26),
  ('Audi'::text, 'S5'::text, 27),
  ('Audi'::text, 'S6'::text, 28),
  ('Audi'::text, 'S7'::text, 29),
  ('Audi'::text, 'S8'::text, 30),
  ('Audi'::text, 'SQ5'::text, 31),
  ('Audi'::text, 'SQ7'::text, 32),
  ('Audi'::text, 'SQ8'::text, 33),
  ('Volkswagen'::text, 'Polo'::text, 0),
  ('Volkswagen'::text, 'Golf'::text, 1),
  ('Volkswagen'::text, 'Passat'::text, 2),
  ('Volkswagen'::text, 'Arteon'::text, 3),
  ('Volkswagen'::text, 'Tiguan'::text, 4),
  ('Volkswagen'::text, 'Touareg'::text, 5),
  ('Volkswagen'::text, 'T-Roc'::text, 6),
  ('Volkswagen'::text, 'T-Cross'::text, 7),
  ('Volkswagen'::text, 'Touran'::text, 8),
  ('Volkswagen'::text, 'Sharan'::text, 9),
  ('Volkswagen'::text, 'ID.3'::text, 10),
  ('Volkswagen'::text, 'ID.4'::text, 11),
  ('Volkswagen'::text, 'ID.5'::text, 12),
  ('Volkswagen'::text, 'ID. Buzz'::text, 13),
  ('Volkswagen'::text, 'Caddy'::text, 14),
  ('Volkswagen'::text, 'Transporter'::text, 15),
  ('Volkswagen'::text, 'Multivan'::text, 16),
  ('Volkswagen'::text, 'Amarok'::text, 17),
  ('Volkswagen'::text, 'Crafter'::text, 18),
  ('Ford'::text, 'Fiesta'::text, 0),
  ('Ford'::text, 'Focus'::text, 1),
  ('Ford'::text, 'Mondeo'::text, 2),
  ('Ford'::text, 'Kuga'::text, 3),
  ('Ford'::text, 'Puma'::text, 4),
  ('Ford'::text, 'EcoSport'::text, 5),
  ('Ford'::text, 'Mustang'::text, 6),
  ('Ford'::text, 'Mach-E'::text, 7),
  ('Ford'::text, 'Bronco'::text, 8),
  ('Ford'::text, 'Explorer'::text, 9),
  ('Ford'::text, 'Ranger'::text, 10),
  ('Ford'::text, 'Transit'::text, 11),
  ('Ford'::text, 'Transit Custom'::text, 12),
  ('Ford'::text, 'Tourneo'::text, 13),
  ('Ford'::text, 'Tourneo Custom'::text, 14),
  ('Ford'::text, 'Galaxy'::text, 15),
  ('Ford'::text, 'S-Max'::text, 16),
  ('Ford'::text, 'B-Max'::text, 17),
  ('Renault'::text, 'Clio'::text, 0),
  ('Renault'::text, 'Megane'::text, 1),
  ('Renault'::text, 'Captur'::text, 2),
  ('Renault'::text, 'Kadjar'::text, 3),
  ('Renault'::text, 'Austral'::text, 4),
  ('Renault'::text, 'Espace'::text, 5),
  ('Renault'::text, 'Talisman'::text, 6),
  ('Renault'::text, 'Twingo'::text, 7),
  ('Renault'::text, 'Zoe'::text, 8),
  ('Renault'::text, 'Megane E-Tech'::text, 9),
  ('Renault'::text, 'Scenic E-Tech'::text, 10),
  ('Renault'::text, '5 E-Tech'::text, 11),
  ('Renault'::text, '4 E-Tech'::text, 12),
  ('Renault'::text, 'Twingo E-Tech'::text, 13),
  ('Renault'::text, 'Arkana'::text, 14),
  ('Renault'::text, 'Rafale'::text, 15),
  ('Renault'::text, 'Master'::text, 16),
  ('Renault'::text, 'Trafic'::text, 17),
  ('Renault'::text, 'Kangoo'::text, 18),
  ('Fiat'::text, '500'::text, 0),
  ('Fiat'::text, 'Panda'::text, 1),
  ('Fiat'::text, 'Tipo'::text, 2),
  ('Fiat'::text, '500X'::text, 3),
  ('Fiat'::text, '500L'::text, 4),
  ('Fiat'::text, 'Doblo'::text, 5),
  ('Fiat'::text, 'Ducato'::text, 6),
  ('Fiat'::text, 'Fullback'::text, 7),
  ('Fiat'::text, 'E-Doblo'::text, 8),
  ('Fiat'::text, 'E-Ducato'::text, 9),
  ('Fiat'::text, '600e'::text, 10),
  ('Fiat'::text, 'Topolino'::text, 11),
  ('Hyundai'::text, 'i10'::text, 0),
  ('Hyundai'::text, 'i20'::text, 1),
  ('Hyundai'::text, 'i30'::text, 2),
  ('Hyundai'::text, 'i30 N'::text, 3),
  ('Hyundai'::text, 'Kona'::text, 4),
  ('Hyundai'::text, 'Kona Electric'::text, 5),
  ('Hyundai'::text, 'Tucson'::text, 6),
  ('Hyundai'::text, 'Santa Fe'::text, 7),
  ('Hyundai'::text, 'Ioniq 5'::text, 8),
  ('Hyundai'::text, 'Ioniq 6'::text, 9),
  ('Hyundai'::text, 'Ioniq 9'::text, 10),
  ('Hyundai'::text, 'Bayon'::text, 11),
  ('Hyundai'::text, 'Staria'::text, 12),
  ('Hyundai'::text, 'Nexo'::text, 13),
  ('Hyundai'::text, 'i40'::text, 14),
  ('Toyota'::text, 'Yaris'::text, 0),
  ('Toyota'::text, 'Yaris Cross'::text, 1),
  ('Toyota'::text, 'Corolla'::text, 2),
  ('Toyota'::text, 'Corolla Cross'::text, 3),
  ('Toyota'::text, 'Camry'::text, 4),
  ('Toyota'::text, 'C-HR'::text, 5),
  ('Toyota'::text, 'RAV4'::text, 6),
  ('Toyota'::text, 'Highlander'::text, 7),
  ('Toyota'::text, 'Land Cruiser'::text, 8),
  ('Toyota'::text, 'Land Cruiser Prado'::text, 9),
  ('Toyota'::text, 'Supra'::text, 10),
  ('Toyota'::text, 'bZ4X'::text, 11),
  ('Toyota'::text, 'Hilux'::text, 12),
  ('Toyota'::text, 'Proace'::text, 13),
  ('Toyota'::text, 'Proace City'::text, 14),
  ('Toyota'::text, 'Aygo'::text, 15),
  ('Toyota'::text, 'Avensis'::text, 16),
  ('Toyota'::text, 'Auris'::text, 17),
  ('Toyota'::text, 'GT86'::text, 18),
  ('Toyota'::text, 'GR Yaris'::text, 19),
  ('Toyota'::text, 'GR Corolla'::text, 20),
  ('Honda'::text, 'Jazz'::text, 0),
  ('Honda'::text, 'Civic'::text, 1),
  ('Honda'::text, 'Accord'::text, 2),
  ('Honda'::text, 'HR-V'::text, 3),
  ('Honda'::text, 'CR-V'::text, 4),
  ('Honda'::text, 'e:Ny1'::text, 5),
  ('Honda'::text, 'Civic Type R'::text, 6),
  ('Honda'::text, 'ZR-V'::text, 7),
  ('Honda'::text, 'NSX'::text, 8),
  ('Opel'::text, 'Corsa'::text, 0),
  ('Opel'::text, 'Corsa-e'::text, 1),
  ('Opel'::text, 'Astra'::text, 2),
  ('Opel'::text, 'Astra Electric'::text, 3),
  ('Opel'::text, 'Insignia'::text, 4),
  ('Opel'::text, 'Mokka'::text, 5),
  ('Opel'::text, 'Mokka-e'::text, 6),
  ('Opel'::text, 'Crossland'::text, 7),
  ('Opel'::text, 'Grandland'::text, 8),
  ('Opel'::text, 'Combo'::text, 9),
  ('Opel'::text, 'Combo-e'::text, 10),
  ('Opel'::text, 'Vivaro'::text, 11),
  ('Opel'::text, 'Vivaro-e'::text, 12),
  ('Opel'::text, 'Movano'::text, 13),
  ('Opel'::text, 'Speedster'::text, 14),
  ('Opel'::text, 'GT'::text, 15),
  ('Peugeot'::text, '108'::text, 0),
  ('Peugeot'::text, '208'::text, 1),
  ('Peugeot'::text, '2008'::text, 2),
  ('Peugeot'::text, 'e-208'::text, 3),
  ('Peugeot'::text, 'e-2008'::text, 4),
  ('Peugeot'::text, '308'::text, 5),
  ('Peugeot'::text, '308 SW'::text, 6),
  ('Peugeot'::text, '3008'::text, 7),
  ('Peugeot'::text, '5008'::text, 8),
  ('Peugeot'::text, '508'::text, 9),
  ('Peugeot'::text, '508 SW'::text, 10),
  ('Peugeot'::text, 'Rifter'::text, 11),
  ('Peugeot'::text, 'Partner'::text, 12),
  ('Peugeot'::text, 'Traveller'::text, 13),
  ('Peugeot'::text, 'Expert'::text, 14),
  ('Peugeot'::text, 'Boxer'::text, 15),
  ('Peugeot'::text, 'Landtrek'::text, 16),
  ('Citroen'::text, 'C1'::text, 0),
  ('Citroen'::text, 'C3'::text, 1),
  ('Citroen'::text, 'C3 Aircross'::text, 2),
  ('Citroen'::text, 'e-C3'::text, 3),
  ('Citroen'::text, 'C4'::text, 4),
  ('Citroen'::text, 'C4 X'::text, 5),
  ('Citroen'::text, 'C4 Cactus'::text, 6),
  ('Citroen'::text, 'C5 Aircross'::text, 7),
  ('Citroen'::text, 'C5 X'::text, 8),
  ('Citroen'::text, 'Berlingo'::text, 9),
  ('Citroen'::text, 'e-Berlingo'::text, 10),
  ('Citroen'::text, 'SpaceTourer'::text, 11),
  ('Citroen'::text, 'e-SpaceTourer'::text, 12),
  ('Citroen'::text, 'C-Elysee'::text, 13),
  ('Citroen'::text, 'C3-XR'::text, 14),
  ('Citroen'::text, 'Jumpy'::text, 15),
  ('Citroen'::text, 'Jumper'::text, 16),
  ('Skoda'::text, 'Fabia'::text, 0),
  ('Skoda'::text, 'Scala'::text, 1),
  ('Skoda'::text, 'Octavia'::text, 2),
  ('Skoda'::text, 'Superb'::text, 3),
  ('Skoda'::text, 'Kamiq'::text, 4),
  ('Skoda'::text, 'Karoq'::text, 5),
  ('Skoda'::text, 'Kodiaq'::text, 6),
  ('Skoda'::text, 'Enyaq iV'::text, 7),
  ('Skoda'::text, 'Enyaq Coupé iV'::text, 8),
  ('Skoda'::text, 'Elroq'::text, 9),
  ('Skoda'::text, 'Citigo'::text, 10),
  ('Skoda'::text, 'Rapid'::text, 11),
  ('Skoda'::text, 'Yeti'::text, 12),
  ('Kia'::text, 'Picanto'::text, 0),
  ('Kia'::text, 'Rio'::text, 1),
  ('Kia'::text, 'Ceed'::text, 2),
  ('Kia'::text, 'Ceed SW'::text, 3),
  ('Kia'::text, 'ProCeed'::text, 4),
  ('Kia'::text, 'XCeed'::text, 5),
  ('Kia'::text, 'Stonic'::text, 6),
  ('Kia'::text, 'Sportage'::text, 7),
  ('Kia'::text, 'Sorento'::text, 8),
  ('Kia'::text, 'Niro'::text, 9),
  ('Kia'::text, 'Niro EV'::text, 10),
  ('Kia'::text, 'EV6'::text, 11),
  ('Kia'::text, 'EV9'::text, 12),
  ('Kia'::text, 'EV3'::text, 13),
  ('Kia'::text, 'EV4'::text, 14),
  ('Kia'::text, 'EV5'::text, 15),
  ('Kia'::text, 'Stinger'::text, 16),
  ('Kia'::text, 'Venga'::text, 17),
  ('Kia'::text, 'Soul'::text, 18),
  ('Nissan'::text, 'Micra'::text, 0),
  ('Nissan'::text, 'Juke'::text, 1),
  ('Nissan'::text, 'Qashqai'::text, 2),
  ('Nissan'::text, 'X-Trail'::text, 3),
  ('Nissan'::text, 'Ariya'::text, 4),
  ('Nissan'::text, 'Leaf'::text, 5),
  ('Nissan'::text, 'Navara'::text, 6),
  ('Nissan'::text, 'Pathfinder'::text, 7),
  ('Nissan'::text, '370Z'::text, 8),
  ('Nissan'::text, 'GT-R'::text, 9),
  ('Nissan'::text, 'Pulsar'::text, 10),
  ('Nissan'::text, 'Note'::text, 11),
  ('Nissan'::text, 'NV200'::text, 12),
  ('Nissan'::text, 'Townstar'::text, 13),
  ('Nissan'::text, 'Interstar'::text, 14),
  ('Mazda'::text, 'Mazda2'::text, 0),
  ('Mazda'::text, 'Mazda3'::text, 1),
  ('Mazda'::text, 'Mazda6'::text, 2),
  ('Mazda'::text, 'CX-3'::text, 3),
  ('Mazda'::text, 'CX-30'::text, 4),
  ('Mazda'::text, 'CX-5'::text, 5),
  ('Mazda'::text, 'CX-60'::text, 6),
  ('Mazda'::text, 'CX-80'::text, 7),
  ('Mazda'::text, 'CX-90'::text, 8),
  ('Mazda'::text, 'MX-30'::text, 9),
  ('Mazda'::text, 'MX-30 e-Skyactiv'::text, 10),
  ('Mazda'::text, 'MX-5'::text, 11),
  ('Mazda'::text, 'MX-5 RF'::text, 12),
  ('Mazda'::text, 'BT-50'::text, 13),
  ('Mazda'::text, 'RX-7'::text, 14),
  ('Mazda'::text, 'RX-8'::text, 15),
  ('Volvo'::text, 'S60'::text, 0),
  ('Volvo'::text, 'S90'::text, 1),
  ('Volvo'::text, 'V60'::text, 2),
  ('Volvo'::text, 'V60 Cross Country'::text, 3),
  ('Volvo'::text, 'V90'::text, 4),
  ('Volvo'::text, 'V90 Cross Country'::text, 5),
  ('Volvo'::text, 'XC40'::text, 6),
  ('Volvo'::text, 'XC40 Recharge'::text, 7),
  ('Volvo'::text, 'XC60'::text, 8),
  ('Volvo'::text, 'XC90'::text, 9),
  ('Volvo'::text, 'EX30'::text, 10),
  ('Volvo'::text, 'EX40'::text, 11),
  ('Volvo'::text, 'EX90'::text, 12),
  ('Volvo'::text, 'EC40'::text, 13),
  ('Volvo'::text, 'C40'::text, 14),
  ('Volvo'::text, 'XC70'::text, 15),
  ('Land Rover'::text, 'Defender 90'::text, 0),
  ('Land Rover'::text, 'Defender 110'::text, 1),
  ('Land Rover'::text, 'Defender 130'::text, 2),
  ('Land Rover'::text, 'Discovery'::text, 3),
  ('Land Rover'::text, 'Discovery Sport'::text, 4),
  ('Land Rover'::text, 'Range Rover'::text, 5),
  ('Land Rover'::text, 'Range Rover Sport'::text, 6),
  ('Land Rover'::text, 'Range Rover Velar'::text, 7),
  ('Land Rover'::text, 'Range Rover Evoque'::text, 8),
  ('Porsche'::text, 'Macan'::text, 0),
  ('Porsche'::text, 'Macan Electric'::text, 1),
  ('Porsche'::text, 'Cayenne'::text, 2),
  ('Porsche'::text, 'Panamera'::text, 3),
  ('Porsche'::text, '911'::text, 4),
  ('Porsche'::text, '911 Turbo'::text, 5),
  ('Porsche'::text, 'Taycan'::text, 6),
  ('Porsche'::text, 'Taycan Cross Turismo'::text, 7),
  ('Porsche'::text, '718 Boxster'::text, 8),
  ('Porsche'::text, '718 Cayman'::text, 9),
  ('Porsche'::text, '918 Spyder'::text, 10),
  ('Dacia'::text, 'Sandero'::text, 0),
  ('Dacia'::text, 'Sandero Stepway'::text, 1),
  ('Dacia'::text, 'Logan'::text, 2),
  ('Dacia'::text, 'Duster'::text, 3),
  ('Dacia'::text, 'Jogger'::text, 4),
  ('Dacia'::text, 'Spring'::text, 5),
  ('Dacia'::text, 'Dokker'::text, 6),
  ('Dacia'::text, 'Lodgy'::text, 7),
  ('Suzuki'::text, 'Swift'::text, 0),
  ('Suzuki'::text, 'Swift Sport'::text, 1),
  ('Suzuki'::text, 'Vitara'::text, 2),
  ('Suzuki'::text, 'S-Cross'::text, 3),
  ('Suzuki'::text, 'Jimny'::text, 4),
  ('Suzuki'::text, 'Ignis'::text, 5),
  ('Suzuki'::text, 'Swace'::text, 6),
  ('Suzuki'::text, 'Across'::text, 7),
  ('Suzuki'::text, 'Baleno'::text, 8),
  ('Suzuki'::text, 'Celerio'::text, 9),
  ('Suzuki'::text, 'SX4'::text, 10),
  ('Suzuki'::text, 'Grand Vitara'::text, 11),
  ('Mitsubishi'::text, 'ASX'::text, 0),
  ('Mitsubishi'::text, 'Eclipse Cross'::text, 1),
  ('Mitsubishi'::text, 'Outlander'::text, 2),
  ('Mitsubishi'::text, 'Outlander PHEV'::text, 3),
  ('Mitsubishi'::text, 'L200'::text, 4),
  ('Mitsubishi'::text, 'Colt'::text, 5),
  ('Mitsubishi'::text, 'Pajero'::text, 6),
  ('Mitsubishi'::text, 'Pajero Sport'::text, 7),
  ('Mitsubishi'::text, 'Space Star'::text, 8),
  ('Mitsubishi'::text, 'Mirage'::text, 9),
  ('Subaru'::text, 'Impreza'::text, 0),
  ('Subaru'::text, 'XV (Crosstrek)'::text, 1),
  ('Subaru'::text, 'Forester'::text, 2),
  ('Subaru'::text, 'Outback'::text, 3),
  ('Subaru'::text, 'Solterra'::text, 4),
  ('Subaru'::text, 'BRZ'::text, 5),
  ('Subaru'::text, 'WRX'::text, 6),
  ('Subaru'::text, 'Levorg'::text, 7),
  ('Subaru'::text, 'Ascent'::text, 8),
  ('Subaru'::text, 'Tribeca'::text, 9),
  ('Jeep'::text, 'Avenger'::text, 0),
  ('Jeep'::text, 'Avenger Electric'::text, 1),
  ('Jeep'::text, 'Renegade'::text, 2),
  ('Jeep'::text, 'Compass'::text, 3),
  ('Jeep'::text, 'Cherokee'::text, 4),
  ('Jeep'::text, 'Grand Cherokee'::text, 5),
  ('Jeep'::text, 'Wrangler'::text, 6),
  ('Jeep'::text, 'Gladiator'::text, 7),
  ('Jeep'::text, 'Wagoneer'::text, 8),
  ('Jeep'::text, 'Grand Wagoneer'::text, 9),
  ('Mini'::text, 'Cooper'::text, 0),
  ('Mini'::text, 'Cooper S'::text, 1),
  ('Mini'::text, 'JCW'::text, 2),
  ('Mini'::text, 'Countryman'::text, 3),
  ('Mini'::text, 'Clubman'::text, 4),
  ('Mini'::text, 'Cabrio'::text, 5),
  ('Mini'::text, 'Aceman'::text, 6),
  ('Mini'::text, 'Cooper Electric'::text, 7),
  ('Mini'::text, 'Countryman Electric'::text, 8),
  ('Tesla'::text, 'Model 3'::text, 0),
  ('Tesla'::text, 'Model 3 Highland'::text, 1),
  ('Tesla'::text, 'Model Y'::text, 2),
  ('Tesla'::text, 'Model Y Juniper'::text, 3),
  ('Tesla'::text, 'Model S'::text, 4),
  ('Tesla'::text, 'Model X'::text, 5),
  ('Tesla'::text, 'Cybertruck'::text, 6),
  ('Tesla'::text, 'Roadster'::text, 7),
  ('Lexus'::text, 'LBX'::text, 0),
  ('Lexus'::text, 'UX'::text, 1),
  ('Lexus'::text, 'UX Electric'::text, 2),
  ('Lexus'::text, 'NX'::text, 3),
  ('Lexus'::text, 'NX Plug-in'::text, 4),
  ('Lexus'::text, 'RX'::text, 5),
  ('Lexus'::text, 'RZ'::text, 6),
  ('Lexus'::text, 'ES'::text, 7),
  ('Lexus'::text, 'LS'::text, 8),
  ('Lexus'::text, 'LC'::text, 9),
  ('Lexus'::text, 'LC Convertible'::text, 10),
  ('Lexus'::text, 'IS'::text, 11),
  ('Lexus'::text, 'RC'::text, 12),
  ('Lexus'::text, 'UX300e'::text, 13),
  ('Lexus'::text, 'LFA'::text, 14),
  ('Jaguar'::text, 'E-Pace'::text, 0),
  ('Jaguar'::text, 'F-Pace'::text, 1),
  ('Jaguar'::text, 'XF'::text, 2),
  ('Jaguar'::text, 'XE'::text, 3),
  ('Jaguar'::text, 'I-Pace'::text, 4),
  ('Jaguar'::text, 'F-Type'::text, 5),
  ('Jaguar'::text, 'F-Type Convertible'::text, 6),
  ('Jaguar'::text, 'XJ'::text, 7),
  ('Jaguar'::text, 'XK'::text, 8),
  ('Seat'::text, 'Ibiza'::text, 0),
  ('Seat'::text, 'Leon'::text, 1),
  ('Seat'::text, 'Leon ST'::text, 2),
  ('Seat'::text, 'Arona'::text, 3),
  ('Seat'::text, 'Ateca'::text, 4),
  ('Seat'::text, 'Tarraco'::text, 5),
  ('Seat'::text, 'Mii'::text, 6),
  ('Seat'::text, 'Toledo'::text, 7),
  ('Seat'::text, 'Alhambra'::text, 8),
  ('Seat'::text, 'Born'::text, 9),
  ('Ferrari'::text, '488 GTB'::text, 0),
  ('Ferrari'::text, '488 Spider'::text, 1),
  ('Ferrari'::text, 'Roma'::text, 2),
  ('Ferrari'::text, 'Portofino'::text, 3),
  ('Ferrari'::text, 'Portofino M'::text, 4),
  ('Ferrari'::text, 'SF90 Stradale'::text, 5),
  ('Ferrari'::text, '296 GTB'::text, 6),
  ('Ferrari'::text, 'Purosangue'::text, 7),
  ('Ferrari'::text, '812 Superfast'::text, 8),
  ('Ferrari'::text, 'F8 Tributo'::text, 9),
  ('Ferrari'::text, 'F8 Spider'::text, 10),
  ('Ferrari'::text, 'Daytona SP3'::text, 11),
  ('Lamborghini'::text, 'Huracan'::text, 0),
  ('Lamborghini'::text, 'Huracan EVO'::text, 1),
  ('Lamborghini'::text, 'Urus'::text, 2),
  ('Lamborghini'::text, 'Urus S'::text, 3),
  ('Lamborghini'::text, 'Urus Performante'::text, 4),
  ('Lamborghini'::text, 'Revuelto'::text, 5),
  ('Lamborghini'::text, 'Aventador'::text, 6),
  ('Lamborghini'::text, 'Aventador SVJ'::text, 7),
  ('Lamborghini'::text, 'Huracan STO'::text, 8),
  ('Maserati'::text, 'Grecale'::text, 0),
  ('Maserati'::text, 'Grecale Trofeo'::text, 1),
  ('Maserati'::text, 'Levante'::text, 2),
  ('Maserati'::text, 'MC20'::text, 3),
  ('Maserati'::text, 'Quattroporte'::text, 4),
  ('Maserati'::text, 'GranTurismo'::text, 5),
  ('Maserati'::text, 'GranCabrio'::text, 6),
  ('Maserati'::text, 'Ghibli'::text, 7),
  ('Maserati'::text, 'MC20 Cielo'::text, 8),
  ('Bentley'::text, 'Continental GT'::text, 0),
  ('Bentley'::text, 'Continental GTC'::text, 1),
  ('Bentley'::text, 'Flying Spur'::text, 2),
  ('Bentley'::text, 'Bentayga'::text, 3),
  ('Bentley'::text, 'Bentayga S'::text, 4),
  ('Bentley'::text, 'Mulliner Batur'::text, 5),
  ('Rolls-Royce'::text, 'Ghost'::text, 0),
  ('Rolls-Royce'::text, 'Phantom'::text, 1),
  ('Rolls-Royce'::text, 'Spectre'::text, 2),
  ('Rolls-Royce'::text, 'Cullinan'::text, 3),
  ('Rolls-Royce'::text, 'Wraith'::text, 4),
  ('Rolls-Royce'::text, 'Dawn'::text, 5),
  ('Aston Martin'::text, 'DB11'::text, 0),
  ('Aston Martin'::text, 'DB12'::text, 1),
  ('Aston Martin'::text, 'Vantage'::text, 2),
  ('Aston Martin'::text, 'DBX'::text, 3),
  ('Aston Martin'::text, 'Vanquish'::text, 4),
  ('Aston Martin'::text, 'DB9'::text, 5),
  ('Aston Martin'::text, 'Rapide'::text, 6),
  ('Aston Martin'::text, 'DBS'::text, 7),
  ('Smart'::text, 'ForTwo'::text, 0),
  ('Smart'::text, 'ForFour'::text, 1),
  ('Smart'::text, '#1'::text, 2),
  ('Smart'::text, '#3'::text, 3),
  ('Smart'::text, 'EQ ForTwo'::text, 4),
  ('Smart'::text, 'EQ ForFour'::text, 5),
  ('SsangYong'::text, 'Rexton'::text, 0),
  ('SsangYong'::text, 'Torres'::text, 1),
  ('SsangYong'::text, 'Torres EVX'::text, 2),
  ('SsangYong'::text, 'Korando'::text, 3),
  ('SsangYong'::text, 'Korando e-Motion'::text, 4),
  ('SsangYong'::text, 'Tivoli'::text, 5),
  ('SsangYong'::text, 'XLV'::text, 6),
  ('Chery'::text, 'Tiggo 4 Pro'::text, 0),
  ('Chery'::text, 'Tiggo 7 Pro'::text, 1),
  ('Chery'::text, 'Tiggo 8 Pro'::text, 2),
  ('Chery'::text, 'Omoda 5'::text, 3),
  ('Chery'::text, 'Omoda 5 EV'::text, 4),
  ('Chery'::text, 'Jaecoo 7'::text, 5),
  ('Chery'::text, 'Jaecoo 8'::text, 6),
  ('Chery'::text, 'iCar 03'::text, 7),
  ('Chery'::text, 'Tiggo Cross'::text, 8),
  ('Chery'::text, 'Arrizo 5 Plus'::text, 9),
  ('Geely'::text, 'Coolray'::text, 0),
  ('Geely'::text, 'Azkarra'::text, 1),
  ('Geely'::text, 'Tugella'::text, 2),
  ('Geely'::text, 'Monjaro'::text, 3),
  ('Geely'::text, 'Emgrand'::text, 4),
  ('Geely'::text, 'Geometry C'::text, 5),
  ('Geely'::text, 'Geometry E'::text, 6),
  ('Geely'::text, 'Okavango'::text, 7),
  ('Geely'::text, 'Preface'::text, 8),
  ('MG'::text, 'ZS'::text, 0),
  ('MG'::text, 'ZS EV'::text, 1),
  ('MG'::text, 'HS'::text, 2),
  ('MG'::text, 'HS PHEV'::text, 3),
  ('MG'::text, 'EHS'::text, 4),
  ('MG'::text, 'MG4'::text, 5),
  ('MG'::text, 'MG4 Electric'::text, 6),
  ('MG'::text, 'MG5'::text, 7),
  ('MG'::text, 'Marvel R'::text, 8),
  ('MG'::text, 'Cyberster'::text, 9),
  ('MG'::text, 'MG3'::text, 10),
  ('MG'::text, 'MG7'::text, 11),
  ('Isuzu'::text, 'D-Max'::text, 0),
  ('Isuzu'::text, 'MU-X'::text, 1),
  ('Isuzu'::text, 'D-Max V-Cross'::text, 2),
  ('Chrysler'::text, 'Pacifica'::text, 0),
  ('Chrysler'::text, '300'::text, 1),
  ('Chrysler'::text, 'Voyager'::text, 2),
  ('Dodge'::text, 'Durango'::text, 0),
  ('Dodge'::text, 'Challenger'::text, 1),
  ('Dodge'::text, 'Charger'::text, 2),
  ('Dodge'::text, 'Hornet'::text, 3),
  ('Lada'::text, 'Niva'::text, 0),
  ('Lada'::text, 'Vesta'::text, 1),
  ('Lada'::text, 'Granta'::text, 2),
  ('Lada'::text, 'Largus'::text, 3),
  ('Daihatsu'::text, 'Terios'::text, 0),
  ('Daihatsu'::text, 'Sirion'::text, 1),
  ('Daihatsu'::text, 'Charade'::text, 2),
  ('Daihatsu'::text, 'Cuore'::text, 3),
  ('Daihatsu'::text, 'Materia'::text, 4)
) as m(brand_name, model_name, sort_order)
join public.vehicle_brands b on b.name = m.brand_name
where not exists (
  select 1 from public.vehicle_models vm
  where vm.brand_id = b.id and vm.name = m.model_name
);
