-- Migration 25: Tam Marka Listesi (Türkiye Piyasası)
-- 6 araç tipi için markalar: otomobil, suv_pickup, elektrikli, minivan_panelvan, ticari, motorsiklet_utv_atv
-- Mevcut markalar silinir, yenileri eklenir (ID değişir, foreign key'ler güncellenir)

-- Mevcut markaları temizle
delete from public.vehicle_models;
delete from public.vehicle_brands;

-- OTOMOBİL
insert into public.vehicle_brands (name, vehicle_type, sort_order) values
  ('Alfa Romeo', 'otomobil', 1),
  ('Audi', 'otomobil', 2),
  ('BMW', 'otomobil', 3),
  ('Chevrolet', 'otomobil', 4),
  ('Chrysler', 'otomobil', 5),
  ('Citroen', 'otomobil', 6),
  ('Cupra', 'otomobil', 7),
  ('Dacia', 'otomobil', 8),
  ('Daewoo', 'otomobil', 9),
  ('Daihatsu', 'otomobil', 10),
  ('DS Automobiles', 'otomobil', 11),
  ('Fiat', 'otomobil', 12),
  ('Ford', 'otomobil', 13),
  ('Honda', 'otomobil', 14),
  ('Hyundai', 'otomobil', 15),
  ('Infiniti', 'otomobil', 16),
  ('Jaguar', 'otomobil', 17),
  ('Kia', 'otomobil', 18),
  ('Lada', 'otomobil', 19),
  ('Lexus', 'otomobil', 20),
  ('Maserati', 'otomobil', 21),
  ('Mazda', 'otomobil', 22),
  ('Mercedes-Benz', 'otomobil', 23),
  ('MG', 'otomobil', 24),
  ('Mini', 'otomobil', 25),
  ('Mitsubishi', 'otomobil', 26),
  ('Nissan', 'otomobil', 27),
  ('Opel', 'otomobil', 28),
  ('Peugeot', 'otomobil', 29),
  ('Porsche', 'otomobil', 30),
  ('Renault', 'otomobil', 31),
  ('Rover', 'otomobil', 32),
  ('Seat', 'otomobil', 33),
  ('Skoda', 'otomobil', 34),
  ('Smart', 'otomobil', 35),
  ('Subaru', 'otomobil', 36),
  ('Suzuki', 'otomobil', 37),
  ('Tofaş', 'otomobil', 38),
  ('Toyota', 'otomobil', 39),
  ('Volkswagen', 'otomobil', 40),
  ('Volvo', 'otomobil', 41);

-- SUV / PICKUP
insert into public.vehicle_brands (name, vehicle_type, sort_order) values
  ('Audi SUV', 'suv_pickup', 1),
  ('BMW SUV', 'suv_pickup', 2),
  ('Chevrolet SUV', 'suv_pickup', 3),
  ('Citroen SUV', 'suv_pickup', 4),
  ('Cupra SUV', 'suv_pickup', 5),
  ('Dacia SUV', 'suv_pickup', 6),
  ('Dodge', 'suv_pickup', 7),
  ('DS SUV', 'suv_pickup', 8),
  ('Fiat SUV', 'suv_pickup', 9),
  ('Ford SUV', 'suv_pickup', 10),
  ('Honda SUV', 'suv_pickup', 11),
  ('Hyundai SUV', 'suv_pickup', 12),
  ('Isuzu', 'suv_pickup', 13),
  ('Jeep', 'suv_pickup', 14),
  ('Kia SUV', 'suv_pickup', 15),
  ('Land Rover', 'suv_pickup', 16),
  ('Lexus SUV', 'suv_pickup', 17),
  ('Mahindra', 'suv_pickup', 18),
  ('Maserati SUV', 'suv_pickup', 19),
  ('Mazda SUV', 'suv_pickup', 20),
  ('Mercedes SUV', 'suv_pickup', 21),
  ('Mitsubishi SUV', 'suv_pickup', 22),
  ('Nissan SUV', 'suv_pickup', 23),
  ('Opel SUV', 'suv_pickup', 24),
  ('Peugeot SUV', 'suv_pickup', 25),
  ('Porsche SUV', 'suv_pickup', 26),
  ('Renault SUV', 'suv_pickup', 27),
  ('Seat SUV', 'suv_pickup', 28),
  ('Skoda SUV', 'suv_pickup', 29),
  ('SsangYong', 'suv_pickup', 30),
  ('Subaru SUV', 'suv_pickup', 31),
  ('Suzuki SUV', 'suv_pickup', 32),
  ('Toyota SUV', 'suv_pickup', 33),
  ('Volkswagen SUV', 'suv_pickup', 34),
  ('Volvo SUV', 'suv_pickup', 35);

-- ELEKTRİKLİ
insert into public.vehicle_brands (name, vehicle_type, sort_order) values
  ('BMW i', 'elektrikli', 1),
  ('BYD', 'elektrikli', 2),
  ('Citroen Electric', 'elektrikli', 3),
  ('CUPRA Born', 'elektrikli', 4),
  ('Dacia Spring', 'elektrikli', 5),
  ('Fiat 500e', 'elektrikli', 6),
  ('Ford Electric', 'elektrikli', 7),
  ('Hyundai Electric', 'elektrikli', 8),
  ('Kia Electric', 'elektrikli', 9),
  ('Mercedes EQ', 'elektrikli', 10),
  ('MG Electric', 'elektrikli', 11),
  ('Mini Electric', 'elektrikli', 12),
  ('Nissan Leaf', 'elektrikli', 13),
  ('Opel Electric', 'elektrikli', 14),
  ('Peugeot Electric', 'elektrikli', 15),
  ('Renault Electric', 'elektrikli', 16),
  ('Skoda Electric', 'elektrikli', 17),
  ('Smart Electric', 'elektrikli', 18),
  ('Tesla', 'elektrikli', 19),
  ('Toyota Electric', 'elektrikli', 20),
  ('Volkswagen ID', 'elektrikli', 21),
  ('Volvo Electric', 'elektrikli', 22);

-- MİNİVAN / PANELVAN
insert into public.vehicle_brands (name, vehicle_type, sort_order) values
  ('Citroen Van', 'minivan_panelvan', 1),
  ('Dacia Van', 'minivan_panelvan', 2),
  ('Fiat Van', 'minivan_panelvan', 3),
  ('Ford Van', 'minivan_panelvan', 4),
  ('Hyundai Van', 'minivan_panelvan', 5),
  ('Mercedes Van', 'minivan_panelvan', 6),
  ('Opel Van', 'minivan_panelvan', 7),
  ('Peugeot Van', 'minivan_panelvan', 8),
  ('Renault Van', 'minivan_panelvan', 9),
  ('Toyota Van', 'minivan_panelvan', 10),
  ('Volkswagen Van', 'minivan_panelvan', 11);

-- TİCARİ
insert into public.vehicle_brands (name, vehicle_type, sort_order) values
  ('BMC', 'ticari', 1),
  ('DAF', 'ticari', 2),
  ('Ford Truck', 'ticari', 3),
  ('Fuso', 'ticari', 4),
  ('Iveco', 'ticari', 5),
  ('MAN', 'ticari', 6),
  ('Mercedes Truck', 'ticari', 7),
  ('Otokar', 'ticari', 8),
  ('Renault Truck', 'ticari', 9),
  ('Scania', 'ticari', 10),
  ('Volkswagen Truck', 'ticari', 11),
  ('Volvo Truck', 'ticari', 12);

-- MOTORSİKLET / UTV / ATV (birleşik)
insert into public.vehicle_brands (name, vehicle_type, sort_order) values
  ('Aprilia', 'motorsiklet_utv_atv', 1),
  ('Arctic Cat', 'motorsiklet_utv_atv', 2),
  ('Benelli', 'motorsiklet_utv_atv', 3),
  ('BMW Motorrad', 'motorsiklet_utv_atv', 4),
  ('Can-Am', 'motorsiklet_utv_atv', 5),
  ('Ducati', 'motorsiklet_utv_atv', 6),
  ('Harley-Davidson', 'motorsiklet_utv_atv', 7),
  ('Honda Moto', 'motorsiklet_utv_atv', 8),
  ('Husqvarna', 'motorsiklet_utv_atv', 9),
  ('Indian', 'motorsiklet_utv_atv', 10),
  ('Kawasaki', 'motorsiklet_utv_atv', 11),
  ('KTM', 'motorsiklet_utv_atv', 12),
  ('Kymco', 'motorsiklet_utv_atv', 13),
  ('Moto Guzzi', 'motorsiklet_utv_atv', 14),
  ('MV Agusta', 'motorsiklet_utv_atv', 15),
  ('Peugeot Moto', 'motorsiklet_utv_atv', 16),
  ('Piaggio', 'motorsiklet_utv_atv', 17),
  ('Polaris', 'motorsiklet_utv_atv', 18),
  ('Royal Enfield', 'motorsiklet_utv_atv', 19),
  ('Suzuki Moto', 'motorsiklet_utv_atv', 20),
  ('SYM', 'motorsiklet_utv_atv', 21),
  ('Triumph', 'motorsiklet_utv_atv', 22),
  ('Vespa', 'motorsiklet_utv_atv', 23),
  ('Yamaha', 'motorsiklet_utv_atv', 24);
